/* ==================================================================
   COMPARE DIRECTORIES COMMAND
   ================================================================== */

import * as vscode from 'vscode';
import * as path from 'path';
import { StructureGenerator } from '../core/generator';
import { StructureConfig } from '../models/config.interface';

export async function compareDirectoryStructures(): Promise<void> {
    const panes = await vscode.window.showOpenDialog({
        canSelectFolders: true,
        canSelectMany: true,
        openLabel: 'Select two folders to compare'
    });
    if (!panes || panes.length !== 2) {
        vscode.window.showErrorMessage('Please pick **exactly two** folders.');
        return;
    }

    const [a, b] = panes;
    const cfg: StructureConfig = {
        includeSize: true,
        sortBy: 'name',
        outputFormat: 'tree'
    };

    const progressOpts = {
        location: vscode.ProgressLocation.Notification,
        title: 'Comparing folders…',
        cancellable: true
    };

    await vscode.window.withProgress(progressOpts, async (progress, token) => {
        progress.report({ message: `Scanning ${a.fsPath}` });
        const genA = new StructureGenerator(
            cfg,
            undefined,
            () => token.isCancellationRequested
        );
        const structA = await genA.generate(a.fsPath);

        if (token.isCancellationRequested) {
            return;
        }

        progress.report({ message: `Scanning ${b.fsPath}` });
        const genB = new StructureGenerator(
            cfg,
            undefined,
            () => token.isCancellationRequested
        );
        const structB = await genB.generate(b.fsPath);

        const report = [
            `# 📁 Directory Comparison`,
            `**Folder 1:** \`${a.fsPath}\``,
            `**Folder 2:** \`${b.fsPath}\``,
            '',
            `## 📂 ${path.basename(a.fsPath)}`,
            '```',
            structA,
            '```',
            '',
            `## 📂 ${path.basename(b.fsPath)}`,
            '```',
            structB,
            '```',
            '',
            '_Generated by Folder Structure Navigator_'
        ].join('\n');

        const doc = await vscode.workspace.openTextDocument(
            vscode.Uri.parse('untitled:directory-compare.md')
        );
        const editor = await vscode.window.showTextDocument(doc);
        await editor.edit(e => e.insert(new vscode.Position(0, 0), report));
    });
}
